/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restauracion;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ander
 */
public class TormarPedido extends javax.swing.JFrame implements Runnable {
    String hora, minutos, segundos, ampm;
    Thread h1;
    
    static double total;
    double sub_total;
    double iv;
    /**
     * Creates new form TormarPedido
     * @param mesaAtender
     * @param mesero
     */
    public TormarPedido(String mesaAtender , String mesero) {
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");
        }catch(Exception e){
            e.printStackTrace();
        } 
        initComponents();
        h1 = new Thread(this);
        h1.start();
        mesaAtend.setText(mesaAtender);
        meseroAtender.setText(mesero);
        
        total = 0;
        sub_total = 0;
        iv = 0;
    }
    
    public void listarPlatos(){
        
        DefaultTableModel tabla = new DefaultTableModel();
        
        String dia = diaPedido.getText();
        String ruta = "Menu/Dias/"+dia+".txt";
        tabla.addColumn("Codigo");
        tabla.addColumn("Plato");
        tabla.addColumn("Descripcion ");
        tabla.addColumn("Tipo");
        tabla.addColumn("Precio ");
       
        Object fila[] = new Object[tabla.getColumnCount()];
        
        File archivo = null;  //apuntar al archivo almancenado DD
        FileReader contenido = null;  //acceder a todo el contenido del archivo
        BufferedReader linea = null; //accede linea a linea al contenido
        
        try{
            archivo = new File(ruta);
            contenido = new FileReader(archivo);
            linea = new BufferedReader(contenido);
            
            String cadena=""; //variable captura los datos del archivo
            while((cadena=linea.readLine()) != null){ //recorre todo el archivo
      
                String dato[] = cadena.split(";");
                fila[0] = dato[1];
                fila[1] = dato[3];
                fila[2] = dato[4];
                fila[3] = dato[2];
                fila[4] = dato[5];
                tabla.addRow(fila);  
                

            }
            
         }catch(IOException e){
           System.out.print("Error creando archivo");
        }
        finally{
            try{
                if(contenido != null){
                    contenido.close();
                }
            }catch(IOException e1){
                System.out.print("Error cerrando archivo");
            }
        }
        verPlatos.setModel(tabla);
        verPlatos.setRowHeight(20);
    } 
    
    private void mensaje(String texto){
        JOptionPane.showMessageDialog(null, texto);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pedidos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIva = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        quitarProduc = new javax.swing.JButton();
        cambios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        verPlatos = new javax.swing.JTable();
        cantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        diaPedido = new javax.swing.JLabel();
        anadir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        meseroAtender = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        meseroAtender1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        fecha = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        mesaAtend = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusCycleRoot(false);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(251, 192, 163));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 113, 40), 4));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(249, 184, 152));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Plato", "Precio Unitario", "Precio Total"
            }
        ));
        jScrollPane2.setViewportView(pedidos);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 55, 490, 200));

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 204));
        jLabel6.setText("SUBTOTAL:");

        txtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSubTotal.setForeground(new java.awt.Color(0, 153, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("IVA:");

        txtIva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtIva.setForeground(new java.awt.Color(255, 51, 0));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 102));
        jLabel8.setText("TOTAL");

        txtTotal.setBackground(new java.awt.Color(255, 255, 255));
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(0, 204, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 520, 50));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("_______________");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 20));

        jLabel5.setBackground(new java.awt.Color(255, 204, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PEDIDO ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 50));

        quitarProduc.setBackground(new java.awt.Color(255, 51, 51));
        quitarProduc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quitarProduc.setForeground(new java.awt.Color(255, 255, 255));
        quitarProduc.setText("QUITAR");
        quitarProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarProducActionPerformed(evt);
            }
        });
        jPanel3.add(quitarProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 90, 30));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 520, 370));

        cambios.setBackground(new java.awt.Color(249, 184, 152));
        cambios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        cambios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        verPlatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Plato", "Descripcion", "Tipo", "Precio"
            }
        ));
        jScrollPane1.setViewportView(verPlatos);

        cambios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 40, 478, 170));
        cambios.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 51, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("OBSERVACIONES:");
        cambios.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        diaPedido.setBackground(new java.awt.Color(255, 204, 51));
        diaPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        diaPedido.setForeground(new java.awt.Color(255, 255, 255));
        cambios.add(diaPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 140, 20));

        anadir.setBackground(new java.awt.Color(255, 51, 0));
        anadir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        anadir.setForeground(new java.awt.Color(255, 255, 255));
        anadir.setText("AGREGAR");
        anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirActionPerformed(evt);
            }
        });
        cambios.add(anadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 110, 40));

        jLabel10.setBackground(new java.awt.Color(255, 204, 51));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PLATOS - BEBIDAS - ADICIONALES - DEL DIA:");
        cambios.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 12, 332, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CANTIDAD POR PLATO Y/O BEBIDA:");
        cambios.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 240, -1));

        observaciones.setColumns(20);
        observaciones.setLineWrap(true);
        observaciones.setRows(6);
        observaciones.setSelectionColor(new java.awt.Color(255, 153, 51));
        jScrollPane3.setViewportView(observaciones);

        cambios.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 310, 70));

        jPanel4.add(cambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 500, 370));

        jPanel5.setBackground(new java.awt.Color(242, 113, 40));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        meseroAtender.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        meseroAtender.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(meseroAtender, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 360, 29));

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Enviar Pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 150, 40));

        meseroAtender1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        meseroAtender1.setForeground(new java.awt.Color(255, 255, 255));
        meseroAtender1.setText("Atendido por:");
        jPanel5.add(meseroAtender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 29));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 1050, 60));

        jPanel7.setBackground(new java.awt.Color(242, 113, 40));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fecha.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 320, 30));

        lbHora.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        lbHora.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 110, 30));

        mesaAtend.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        mesaAtend.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(mesaAtend, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 230, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tomar Pedido:");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1051, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirActionPerformed
        DefaultTableModel tabla = new DefaultTableModel();
        int filaSel = verPlatos.getSelectedRow();
        try{ 
            String codigo,plato,descripcion,tipo,precio,cant,importe;
            double calcula=0.0,x=0.0,iva=0.0;
            int canti=0;
            
            if(filaSel==-1){
                JOptionPane.showMessageDialog (null,"Debe seleccionar un producto","Advertecia",JOptionPane.WARNING_MESSAGE);
            }else {
                tabla=(DefaultTableModel) verPlatos.getModel();
                codigo = verPlatos.getValueAt(filaSel,0).toString();
                plato = verPlatos.getValueAt(filaSel,1).toString();
                descripcion = verPlatos.getValueAt(filaSel,2).toString();
                tipo = verPlatos.getValueAt(filaSel,3).toString();
                precio = verPlatos.getValueAt(filaSel,4).toString();
                cant = cantidad.getText();
                
                //CALCULOS
                
               x=(Double.parseDouble(precio)* Integer.parseInt(cant));
               importe =String.valueOf(x);
               
               tabla=(DefaultTableModel) pedidos.getModel();
               String filaelemento[] = {cant,plato,precio,importe};
               tabla.addRow(filaelemento);
               
               calcula = (Double.parseDouble(precio)* Integer.parseInt(cantidad.getText()));
               
               total=(int) (total+calcula);
               iva=total*0.16;
               iv = (int) iva;
               sub_total=(int) (total-iva);
               
               txtTotal.setText(""+total);
               txtSubTotal.setText(""+sub_total);
               txtIva.setText(""+iv);
               
            }
        }catch (HeadlessException | NumberFormatException e){
             JOptionPane.showMessageDialog (null,"Seleccione un producto","Advertencia",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_anadirActionPerformed

    private void quitarProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarProducActionPerformed
        double x=0.0, ivaAct=0.0,subTotalAct=0.0,precioActual=0.0,importe=0.0;
        int filaSel;
        int resp;
        
        try {
           filaSel = pedidos.getSelectedRow();
           if(filaSel==-1){
               JOptionPane.showMessageDialog (null,"Debe seleccionar un producto","Advertecia",JOptionPane.WARNING_MESSAGE);
           }else{
             resp=JOptionPane.showConfirmDialog (null,"Esta seguro de eliminar este producto","Eliminar",JOptionPane.YES_NO_OPTION); 
             if(resp == JOptionPane.YES_OPTION){
                 importe=Double.parseDouble(pedidos.getValueAt(filaSel,3).toString());
                 precioActual =Double.parseDouble(txtTotal.getText())-importe;
                 total = precioActual;
                 txtTotal.setText(""+total);
                 ivaAct=total*0.16;
             }
           } 
        } catch (Exception e) {
        }
    }//GEN-LAST:event_quitarProducActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadir;
    private javax.swing.JPanel cambios;
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel diaPedido;
    private javax.swing.JLabel fecha;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel mesaAtend;
    private javax.swing.JLabel meseroAtender;
    private javax.swing.JLabel meseroAtender1;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JTable pedidos;
    private javax.swing.JButton quitarProduc;
    private javax.swing.JLabel txtIva;
    private javax.swing.JLabel txtSubTotal;
    private javax.swing.JLabel txtTotal;
    private javax.swing.JTable verPlatos;
    // End of variables declaration//GEN-END:variables
 
    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        Calendar calendar = Calendar.getInstance();
        String [] dias = {"","Domingo","Lunes","Martes","Miercoles","Jueves","Viernes","Sabado"};
        String [] meses = {"","Enero","Febrero","Marzo","Abril","Mayo","junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"};
        fecha.setText(dias[(calendar.get(7))]+" - "+(calendar.get(5))+" de "+meses[(calendar.get(2)+1)]+" del "+(calendar.get(1))+" ,");
        diaPedido.setText(dias[(calendar.get(7))]);
        listarPlatos();
        while (ct == h1) {
            calcula();
            lbHora.setText(hora + ":" + minutos + ":" + segundos + " " + ampm);
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            }
        }
    }
    public void calcula() {
        Calendar calendario = new GregorianCalendar();
        Date fechaHoraActual = new Date();
        calendario.setTime(fechaHoraActual);
        ampm = calendario.get(Calendar.AM_PM) == Calendar.AM ? "AM" : "PM";
        if (ampm.equals("PM")) {
            int h = calendario.get(Calendar.HOUR_OF_DAY);
            hora = h > 9 ? "" + h : "0" + h;
        } else {
            hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }



}
